name: refyne_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  injectable: ^1.5.3
  get_it: ^7.2.0
  flutter_bloc: ^7.0.1
  image_picker: ^0.8.4+10
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_image_compress: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  injectable_generator: any
  build_runner: any

flutter:
  uses-material-design: true
